updated land tiles to use NOAA coastlines and Copernicus S2 kml
NASA-IMPACT/hls-land_tiles pull request #1
Opened 2021-05-05 14:23 UTC by freitagb

2021-06-24 10:32 UTC, ciaranevans requested changes
Most of these comments are questions/small vanity changes @freitagb so feel free to ignore/challenge them!

If it makes the right data, then I'd say the codes gucci, seems to do what it should!

2021-06-24 10:32 UTC, ciaransweet commented on README.TXT
> +	b) Lower resolution shapefiles are available. If users want to increase processing time with a lower resolution shapefile, update the file path in the params.json file
Forgive my naivety - do you mean `reduce processing time with a lower resolution shapefile`?

2021-06-24 10:32 UTC, ciaransweet commented on README.TXT
> +2. The KML of the MGRS grid is provided via Copernicus and can be converted as stored as a geojson using create_S2_geojson.py:
```suggestion
2. The KML of the MGRS grid is provided via Copernicus and can be converted and stored as a geojson using create_S2_geojson.py:
```

2021-06-24 10:32 UTC, ciaranevans commented on HLS_land_tiles.py
> +class hls_land_tiles:
This should really be in PascalCase

```suggestion
class HLSLandTiles:
```

2021-06-24 10:32 UTC, ciaranevans commented on HLS_land_tiles.py
> +    def get_S2grid_from_kml(self,kml_url):
```suggestion
    def get_s2_grid_from_kml(self,kml_url):
```

2021-06-24 10:32 UTC, ciaranevans commented on HLS_land_tiles.py
> +    def get_land_mask(self,land_shpfile):
```suggestion
    def get_land_mask(self, land_shpfile):
```

2021-06-24 10:32 UTC, ciaranevans commented on HLS_land_tiles.py
> +            self.land_polys.append(Polygon(tile["geometry"]["coordinates"][0]).buffer(0.01,cap_style=3,join_style=3))
```suggestion
            self.land_polys.append(Polygon(tile["geometry"]["coordinates"][0]).buffer(0.01, cap_style=3, join_style=3))
```

2021-06-24 10:32 UTC, ciaranevans commented on HLS_land_tiles.py
> +        S2_complete_grid = xmltodict.parse(requests.get(kml_url).text)
```suggestion
        s2_complete_grid = xmltodict.parse(requests.get(kml_url).text)
```

2021-06-24 10:32 UTC, ciaranevans commented on HLS_land_tiles.py
> +        objects = S2_complete_grid["kml"]["Document"]["Folder"][0]["Placemark"]
```suggestion
        objects = s2_complete_grid["kml"]["Document"]["Folder"][0]["Placemark"]
```

2021-06-24 10:32 UTC, ciaranevans commented on README.TXT
> +2. The KML of the MGRS grid is provided via Copernicus and can be converted as stored as a geojson using create_S2_geojson.py:
@freitagb why do you create the GeoJSON? Is it for other purposes than making the HLS list?

2021-07-08 15:26 UTC, merged

2021-07-16 15:13 UTC, freitagb commented
Hello,
    
           I recently transitioned to NASA and no longer check my uah
    email. Please reach out to me at my new email address
    ***@***.***
    
    Thanks,
          Brian